version: "3"

services:
  base-ello:
    container_name: base-ello
    build:
      context: "."
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
    ports:
      - 88:80
    restart: unless-stopped
    tty: true
    dns:
      - 8.8.8.8
    command: /bin/bash -c "cd /var/www/html && composer install --prefer-dist && chmod -R 777 storage/ && apachectl -D FOREGROUND"
    environment:
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      # DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - ello

networks:
  ello:
    driver: bridge
