name: Tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set directory permissions
      run: chmod -R 777 .

    - name: Build the docker-compose stack
      run: docker-compose up -d --build

    - name: Check running containers
      run: docker ps -a

    - name: Check docker logs
      run: docker-compose logs base-ello

    - name: Run phpcs
      run: docker-compose exec -T base-ello vendor/bin/phpcs

    - name: Run phpunit
      run: docker-compose exec -T base-ello vendor/bin/phpunit -c phpunit.xml
